### ISSUE TITLE
Could not find 'exportgraphics' function or variable

### ISSUE THREAD

**Issue by Laichunli** [xrysats97/EEG-Emotion-Recognition#1]
Hello，Thank you very much for sharing，When I run the simulationDEAP file, I get an error: Cannot find 'exportgraphics' function or variable.
![01DBD8DE0107AF5267877B706FF23980](https://user-images.githubusercontent.com/78184402/160524842-ddf7c97b-e2a1-46c5-96db-7b77e397b215.png)
![F3E6588E4AEA7FB3D11235045C727954](https://user-images.githubusercontent.com/78184402/160524869-4668700e-052f-4931-a499-d02efb6ab8f7.png)
.

**Comment by thodkatz** [comment]
Hi! Thank you for using the code :)
Can you please tell me what version of Matlab do you use?
Function: `exportgraphics()` was introduced to Matlab 2020a

**Comment by Laichunli** [comment]
> 你好！感谢您使用代码 :) 您能告诉我您使用的是哪个版本的 Matlab 吗？ 功能：`exportgraphics()`已引入Matlab 2020a

2018b

**Comment by Laichunli** [comment]
> exportgraphics()

Thank you for your suggestion, I found this function in another version and the problem is solved.

**Comment by thodkatz** [comment]
You are welcome :)
